name: Terraform Destroy
on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3
      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Change to your region if needed
      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
      # Step 5: Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve

